# After deployment of infrastructure, one needs to set three variables in App Service:
# NODE_ENV = production
# SECRET = ...
# CONNECTIONSTRING = connection string to Cosmos DB with url-encoding of equality symbols: %3D

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'Omegapoint Lab'
  
  # Web app name
  webAppName: 'joel-lab2-webapp'
  
  # Environment name
  environmentName: 'production'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Pave
  displayName: Pave the infrastructure
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Omegapoint Lab (d2245c54-7bbf-4a04-8b8c-e05622b29fc5)'
          subscriptionId: 'd2245c54-7bbf-4a04-8b8c-e05622b29fc5'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'VstsRG-joehar-860c'
          location: 'Central US'
          templateLocation: 'Linked artifact'
          csmFile: 'ArmTemplate/template.json'
          deploymentMode: 'Incremental'