# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'Omegapoint Lab'
  
  # Web app name
  webAppName: 'joel-lab2-webapp'
  
  # Environment name
  environmentName: 'production'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Pave
  displayName: Pave the infrastructure
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Omegapoint Lab (d2245c54-7bbf-4a04-8b8c-e05622b29fc5)'
          subscriptionId: 'd2245c54-7bbf-4a04-8b8c-e05622b29fc5'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'VstsRG-joehar-860c'
          location: 'Central US'
          templateLocation: 'Linked artifact'
          csmFile: 'ArmTemplate/template.json'
          deploymentMode: 'Incremental'